environment:
  global:
    CI: true

  matrix:
    # node.js
    - nodejs_version: "7"     # latest 7
    - nodejs_version: "7.6"   # latest build of 7.6
    - nodejs_version: "7.6.0" # minimal required

# not sure about this
#cache:
#  - node_modules

install:
  - echo Hello, my friendly log reader
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - echo In javascript we used to test and then build

test_script:
  - node --version
  - npm --version
  - npm run test:all

before_deploy:
  - npm run build
