version: '3'
services:
  sut:
    tty: true
    command: test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/opt/app/src
    environment:
      - NODE_ENV=development
